#   Poke
#
#   [Discord] https://discord.gg/7eYqtWxZtp
#   [GitHub] https://github.com/pxlmo/rfp
#   [Documentation] --coming soon--

database:
  username: "pokes"
  password: "default"

pokeSound: "ENTITY_EXPERIENCE_ORB_PICKUP"

messages:
  onJoin: "You have been poked {amount} time(s) while you were gone"
  onPoke: "{player} poked you!"