name: Poke
version: '${project.version}'
main: me.lewd.poke.Main
api-version: 1.19
authors: [ 2lewd4u ]
description: Facebook pokes but in Minecraft

commands:
  poke:
    description: poke someone
    usage: /<command>
    permission: pokes.poke

permissions:
  pokes.poke:
    description: permission to poke
    default: true